import { NextResponse } from "next/server";

import { sendAiMessageSchema } from "@/domains/ai/schemas/ai.schema";
import { sendAiMessage } from "@/domains/ai/services/ai.service";
import { getCurrentUser } from "@/platform/auth/get-current-user";

const ENCODER = new TextEncoder();

/** Small enough that each chunk still reads as "arriving," large enough not to spam the client with hundreds of writes on a long reply. */
const CHUNK_SIZE = 24;

function sseEvent(event: string, data: unknown): Uint8Array {
  return ENCODER.encode(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);
}

/** Between a tool_call event and the next one, or the first text chunk — long enough to read as a distinct step, short enough not to feel sluggish for a turn with several tool calls. */
const TOOL_EVENT_DELAY_MS = 250;
const TEXT_CHUNK_DELAY_MS = 15;

/**
 * Streams the ops assistant's turn to the browser as a sequence of real
 * events, rather than making the client wait for the whole Server Action
 * round-trip and then see only the final text.
 *
 * This is honest about what it streams: `sendAiMessage` (the same function
 * the non-streaming Server Action calls — orchestrator, tool-use loop,
 * approval gate, persistence, all untouched) still runs to completion
 * first, so every event below describes something that has *already*
 * happened — tool calls have already executed (or been proposed for
 * approval) and the final answer has already been generated by the time
 * anything is sent. What's streamed is *delivery*, sequenced to read like
 * the turn's real timeline (tool calls, in the order the Orchestrator made
 * them, then the final answer in chunks) — not live generation. True
 * model-level token streaming, interleaved with live tool-call detection,
 * would need `StreamEvent` to carry tool_use blocks, which it doesn't yet
 * (see packages/ai/README.md) — extending that is a provider-layer change,
 * deliberately not being made right now. This still gets the real product
 * win (a live-feeling assistant that visibly "does things" before it
 * answers) without it.
 */
export async function POST(request: Request) {
  const actor = await getCurrentUser();
  const body = await request.json();
  const input = sendAiMessageSchema.parse(body);

  const result = await sendAiMessage(actor, input);

  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      for (const call of result.toolCalls) {
        controller.enqueue(
          sseEvent("tool_call", {
            name: call.name,
            status: call.status,
            output: call.output,
            actionId: call.actionId,
          }),
        );
        await new Promise((resolve) =>
          setTimeout(resolve, TOOL_EVENT_DELAY_MS),
        );
      }

      for (let i = 0; i < result.assistantMessage.length; i += CHUNK_SIZE) {
        controller.enqueue(
          sseEvent("chunk", {
            text: result.assistantMessage.slice(i, i + CHUNK_SIZE),
          }),
        );
        // Yield to the event loop between chunks so the browser actually
        // renders progressively instead of receiving one buffered write.
        await new Promise((resolve) =>
          setTimeout(resolve, TEXT_CHUNK_DELAY_MS),
        );
      }

      controller.enqueue(
        sseEvent("done", {
          conversationId: result.conversationId,
          configured: result.configured,
          pendingApproval: result.pendingApproval,
          escalated: result.escalated,
        }),
      );
      controller.close();
    },
  });

  return new NextResponse(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache, no-transform",
      Connection: "keep-alive",
    },
  });
}
